name: nloffice_hrm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.3
  crypto: ^3.0.3
  adaptive_theme: ^3.3.0
  localize_and_translate: ^4.1.1
  mysql_client: ^0.0.27
  animate_do: ^3.0.2
  http: ^1.2.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/lang/
