name: hrm_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD
  assets:
    - assets/images/
=======

assest:
  assets/images/
>>>>>>> dfd67911de0e794b4a5da77f8d235366816ee73c
