name: nloffice_hrm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.9.3+1
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  adaptive_theme: ^3.3.0
  localize_and_translate: ^4.1.1
  mysql_client: ^0.0.27
  animate_do: ^3.0.2
  http: ^1.2.0
  velocity_x: 4.1.0
  pull_to_refresh_flutter3: ^2.0.1
  geolocator: ^9.0.2
  rx_shared_preferences: ^3.0.0
  custom_clippers: ^2.0.0
  easy_localization: ^3.0.2
  device_info_plus: ^9.0.2
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  singleton: ^0.0.3-nullsafety
  synchronized: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/"
  adaptive_icon_foreground: "assets/images/"
  adaptive_icon_background: "#5e17eb"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/
