List<String> majors = [
  // Công nghệ thông tin (IT)
  "Kỹ thuật phần mềm",
  "Hệ thống thông tin",
  "Quản lý cơ sở dữ liệu",
  "An ninh mạng",
  "Kỹ thuật mạng",
  "Phát triển trò chơi",
  "Trí tuệ nhân tạo",
  "Điện toán đám mây",
  "Thông tin kinh doanh",
  "Dữ liệu lớn",
  "Khoa học dữ liệu",
  "Phân tích dữ liệu",
  "Quản trị hệ thống",
  "Phát triển Blockchain",
  "Điện toán lượng tử",
  "Học máy",
  "Kỹ thuật rô-bốt",
  "Phát triển web",
  "Phát triển ứng dụng di động",
  "Bảo mật mạng",
  "Phát triển thương mại điện tử",

  // Kế toán (Accounting)
  "Hệ thống thông tin kế toán",
  "Kế toán pháp y",
  "Kiểm toán",
  "Thuế",
  "Quản lý tài chính",
  "Báo cáo tài chính",
  "Kế toán quản trị",
  "Kế toán quốc tế",
  "Kế toán chi phí",
  "Kế toán công",
  "Kế toán phi lợi nhuận",
  "Kế toán nhà nước",
  "Kiểm toán nội bộ",
  "Lập kế hoạch tài chính",
  "Phân tích đầu tư",
  "Tài chính doanh nghiệp",
  "Mô hình tài chính",
  "Khoa học toán học bảo hiểm",
  "Kế toán bất động sản",
  "Kế toán và Luật kinh doanh",

  // Chăm sóc khách hàng (Customer Service)
  "Quản lý hỗ trợ khách hàng",
  "Quản lý quan hệ khách hàng (CRM)",
  "Công nghệ dịch vụ khách hàng",
  "Dịch vụ khách hàng",
  "Phân tích phản hồi khách hàng",
  "Hỗ trợ sản phẩm",
  "Ủng hộ khách hàng",
  "Vẽ bản đồ hành trình khách hàng",
  "Quản lý thành công khách hàng",
  "Giao tiếp với khách hàng",
  "Dịch vụ khách hàng B2B",
  "Dịch vụ khách hàng bán lẻ",
  "Dịch vụ khách hàng thương mại điện tử",
  "Lòng trung thành thương hiệu",
  "Đào tạo khách hàng",
  "Dịch vụ khách hàng đa kênh",

  // Marketing
  "Marketing quốc tế",
  "Quản lý thương hiệu",
  "Truyền thông marketing",
  "Chiến lược nội dung",
  "Marketing thương mại điện tử",
  "Lập kế hoạch và marketing sự kiện",
  "Phân tích marketing",
  "Quảng cáo kỹ thuật số",
  "Quan hệ công chúng",
  "Hành vi người tiêu dùng",
  "Quảng cáo trên mạng xã hội",
  "Marketing sản phẩm",
  "Marketing bán lẻ",
  "Phân khúc thị trường",
  "Marketing chiến lược",
  "Marketing di động",
  "Marketing trực tiếp",
  "SEO/SEM",
  "Marketing liên kết",
  "Marketing qua email",
  "Marketing qua người ảnh hưởng",
  "Quảng cáo sáng tạo",

  // Nhân sự (Human Resources)
  "Quản trị nhân sự",
  "Thu hút nhân tài",
  "Phát triển lãnh đạo",
  "Phát triển tổ chức",
  "Quan hệ lao động",
  "Cải thiện phúc lợi và tiền lương",
  "Phân tích nhân sự",
  "Tương tác với nhân viên",
  "Học tập và phát triển",
  "Quản lý lực lượng lao động",
  "Giải quyết xung đột",
  "Chiến lược duy trì nhân viên",
  "Công nghệ nhân sự",
  "Đa dạng và bao gồm",
  "Sức khoẻ nhân viên",
  "Quản lý hiệu suất",
  "Quản lý nhân sự chiến lược",
  "Tuân thủ nhân sự",
  "Văn hóa nơi làm việc",
  "Lập kế hoạch kế nhiệm",
  "Tư vấn nhân sự",

  // Các ngành khác
  "Quản trị kinh doanh",
  "Nghiên cứu marketing",
  "Quản lý dự án",
  "Quản lý chuỗi cung ứng",
  "Phân tích kinh doanh",
  "Quản lý quy trình kinh doanh",
  "Kinh tế học",
  "Hệ thống thông tin quản lý",
  "Quan hệ công chúng",
  "Thiết kế đồ họa",
];
