List<String> universityNames1 = [
  "Trường Đại học Khoa học Xã hội & Nhân văn (ĐHQG HN)",
  "Trường Đại học Kỹ thuật Công nghiệp (ĐH Thái Nguyên)",
  "Trường Đại học Cần Thơ",
  "Trường Đại học Sư phạm Kỹ thuật TP. HCM",
  "Trường Đại học Bách khoa (ĐHQG TP. HCM)",
  "Trường Đại học Vinh",
  "Trường Đại học Đà Lạt",
  "Trường Đại học Kinh tế Quốc dân",
  "Trường Đại học Bách Khoa (ĐH Đà Nẵng)",
  "Trường Đại học Hàng hải Việt Nam",
  "Trường Đại học Sư phạm Hà Nội",
  "Trường Đại học Nông nghiệp Hà Nội",
  "Trường Đại học Sư phạm TP. HCM",
  "Trường Đại học Nông Lâm TP. HCM",
  "Trường Đại học Sư phạm (ĐH Huế)",
  "Trường Đại học Ngoại thương",
  "Trường Đại học Nha Trang",
  "Trường Đại học Thương mại",
  "Trường Đại học Dân lập Hải Phòng",
  "Trường Đại học Dân lập Văn Lang",
  "Trường Đại học Bách khoa Hà Nội",
  "Trường Đại học Giao thông Vận tải, Hà Nội",
  "Trường Đại học Kiến trúc Hà Nội",
  "Trường Đại học Luật Hà Nội",
  "Trường Đại học Mỏ Địa chất",
  "Trường Đại học Thuỷ lợi",
  "Trường Đại học Nông Lâm (ĐH Thái Nguyên)",
  "Trường Đại học Sư phạm (ĐH Thái Nguyên)",
  "Trường Đại học Thể dục Thể thao Bắc Ninh",
  "Trường Đại học Hải Phòng",
  "Trường Đại học Bách khoa - Đại học Đà Nẵng"
      "Trường Đại học Khoa học (ĐH Huế)",
  "Trường Đại học Nông Lâm (ĐH Huế)",
  "Trường Đại học Ngoại ngữ (ĐH Đà Nẵng)",
  "Trường Đại học Duy Tân",
  "Trường Đại học Giao thông Vận tải TP. HCM",
  "Trường Đại học Kiến trúc TP. HCM",
  "Trường Đại học Kinh tế TP. HCM",
  "Trường Đại học Luật TP. HCM",
  "Trường Đại học Kinh tế (ĐH Đà Nẵng)",
  "Trường Đại học Dân lập Hồng Bàng",
  "Học viện Tài chính",
  "Trường Đại học Sư phạm Thể dục Thể thao Hà Nội",
  "Trường Đại học Lao động Xã hội",
  "Trường Đại học Hùng Vương",
  "Trường Đại học Lâm nghiệp",
  "Trường Đại học Sư phạm Hà Nội 2",
  "Trường Đại học Quy Nhơn",
  "Trường Đại học Dân lập Yersin Đà Lạt",
  "Trường Đại học Tây Nguyên",
  "Trường Đại học Văn hóa TP. HCM",
  "Trường Đại học Ngoại ngữ - Tin học TP. HCM",
  "Trường Đại học Tôn Đức Thắng",
  "Trường Đại học Công nghệ TP. HCM",
  "Trường Đại học Ngoại ngữ (ĐH Huế)",
  "Trường Đại học Kinh tế (ĐH Huế)",
  "Trường Đại học Mở TP. HCM",
  "Trường Đại học Bà Rịa Vũng Tàu",
  "Trường Đại học Kinh tế Tài chính TP. HCM",
  "Trường Đại học An Giang",
  "Trường Đại học Kinh doanh và Công nghệ HN",
  "Trường Đại học Dân lập Thăng Long",
  "Trường Đại học Dân lập Phương Đông",
  "Trường Đại học Hồng Đức",
  "Trường Đại học Sư phạm Kỹ thuật Hưng Yên",
  "Học viện Ngân hàng",
  "Trường Đại học Công đoàn",
  "Học viện Kỹ thuật quân sự",
  "Trường Đại học TDTT Đà Nẵng",
  "Viện Đại học Mở Hà Nội",
  "Trường Đại học Hà Tĩnh",
  "Trường Đại học Ngân hàng TP. HCM",
  "Trường Đại học Công nghiệp TP. HCM",
  "Trường Đại học Công nghiệp Hà Nội",
  "Trường Đại học Sân khấu Điện ảnh Hà Nội",
  "Trường Đại học Sư phạm Kỹ thuật Nam Định",
  "Trường Đại học Sài Gòn",
  "Trường Đại học Trà Vinh",
  "Trường Đại học Mỹ thuật TP. HCM",
  "Trường Đại học Phú Yên",
  "Trường Đại học Tây Bắc",
  "Trường Đại học Đồng Tháp",
  "Trường Đại học Sư phạm Kỹ thuật Vinh",
  "Trường Đại học Quốc tế Sài Gòn",
  "Học viện Công nghệ Bưu chính Viễn thông",
  "Trường Đại học Lạc Hồng, Đồng Nai",
  "Học viện Quản lý giáo dục",
  "Trường Đại học Mỹ thuật Công nghiệp, Hà Nội",
  "Trường Đại học Sư phạm (ĐH Đà Nẵng)",
  "Trường Đại học Điều dưỡng Nam Định",
  "Trường Đại học Điện lực",
  "Trường Đại học Xây dựng Hà Nội",
  "Nhạc viện TP. Hồ Chí Minh",
  "Trường Đại học Bạc Liêu",
  "Trường Đại học Kinh tế QTKD (ĐH Thái Nguyên)",
  "Trường Đại học Kinh tế Kỹ thuật Công nghiệp, Hà Nội",
  "Trường Đại học Dân lập Lương Thế Vinh",
  "Trường Đại học Hà Nội",
  "Trường Đại học Sư phạm Thể dục Thể thao TP. HCM",
  "Trường Đại học Thể dục Thể thao TP. HCM",
  "Học viện Ngoại giao",
  "Học viện Lục quân",
  "Trường Đại học Tiền Giang",
  "Trường Đại học Kinh tế Công nghiệp Long An",
  "Trường Đại học Đông Á Đà Nẵng",
  "Trường Đại học Kinh tế (ĐHQG HN)",
  "Trường Đại học Quảng Bình",
  "Trường Đại học KHXH&NV (ĐHQG TP. HCM)",
  "Trường Đại học Giáo dục (ĐHQG HN)",
  "Trường Đại học KHTN (ĐHQG HN)",
  "Trường Đại học Sao Đỏ",
  "Trường Đại học Quốc tế (ĐHQG TP. HCM)",
  "Trường Đại học Công nghệ (ĐHQG HN)",
  "Trường Đại học Ngoại ngữ (ĐHQG HN)",
  "Trường Đại học Hoa Sen",
  "Trường Đại học Kinh tế - Luật (ĐHQG TP. HCM)",
  "Trường Đại học KHTN (ĐHQG TP. HCM)",
  "Học viện An ninh Nhân dân",
  "Học viện Cảnh sát Nhân dân",
  "Trường Đại học An ninh Nhân dân, TP. HCM",
  "Trường Đại học Cảnh sát Nhân dân, TP. HCM",
  "Trường Đại học Phòng cháy chữa cháy",
  "Trường Đại học Phạm Văn Đồng, Quảng Ngãi",
  "Trường Đại học Trần Quốc Tuấn",
  "Trường Đại học Trần Đại Nghĩa",
  "Trường Đại học Hoa Lư",
  "Trường Đại học Kiến trúc Đà Nẵng",
  "Trường Đại học CNTT (ĐHQG TP. HCM)",
  "Trường Đại học FPT",
  "Trường Đại học Tài chính – Marketing",
  "Trường Đại học Chu Văn An",
  "Trường Đại học Bình Dương",
  "Trường Đại học Đồng Nai",
  "Trường Đại học Văn hóa Hà Nội",
  "Trường Đại học Văn Hiến",
  "Trường Đại học CNTT và Truyền thông (ĐH Thái Nguyên)",
  "Trường Đại học Công nghệ Giao thông vận tải",
  "Trường Đại học Khoa học (ĐH Thái Nguyên)",
  "Trường Đại học Hải Dương",
  "Trường Đại học Thái Bình",
  "Trường Đại học Văn hóa Thể thao và Du lịch Thanh Hóa",
  "Trường Đại học Phú Xuân",
  "Trường Đại học Quang Trung",
  "Trường Đại học Công nghiệp Quảng Ninh",
  "Trường Đại học Tây Đô",
  "Trường Đại học Kinh tế - Kỹ thuật Bình Dương",
  "Đại học Đà Nẵng",
  "Trường Đại học Quảng Nam",
  "Trường Đại học Chính trị",
  "Trường Đại học Phan Thiết",
  "Trường Đại học Công nghiệp Việt Trì",
  "Trường Đại học Hòa Bình",
  "Trường Đại học Thành Đô",
  "Trường Đại học Công nghệ Sài Gòn",
  "Trường Đại học Nông Lâm Bắc Giang",
  "Trường Đại học Công nghệ Đông Á",
  "Trường Đại học Công nghệ Thông tin Gia Định",
  "Trường Đại học Hà Hoa Tiên",
  "Trường Đại học Tài nguyên Môi trường TP.HCM",
  "Trường Đại học Xây dựng miền Tây",
  "Trường Đại học Nam Cần Thơ",
  "Trường Đại học Cửu Long",
  "Trường Đại học Tài nguyên và Môi trường Hà Nội",
  "Trường Đại học Mỹ thuật Việt Nam",
  "Trường Đại học Công nghệ Đồng Nai",
  "Trường Đại học Thủ Dầu Một",
  "Trường Đại học Tư thục Công nghệ và Quản lý Hữu Nghị",
  "Trường Đại học Thái Bình Dương",
  "Học viện Hàng không Việt Nam",
  "Trường Đại học Kỹ thuật – Công nghệ Cần Thơ",
  "Trường Đại học Công nghiệp Thực phẩm TP. HCM",
  "Trường Đại học Xây dựng Miền Trung",
  "Trường Đại học Công nghệ Miền Đông",
  "Trường Đại học Quốc tế Miền Đông",
  "Trường Đại học Tài chính - Quản trị kinh doanh",
  "Trường Đại học Nguyễn Tất Thành",
  "Trường Đại học Sư phạm Kỹ thuật Vĩnh Long",
  "Trường Cao đẳng Công nghệ Viettronics",
  "Trường Cao đẳng Cơ khí luyện kim",
  "Trường Cao đẳng Công nghệ Hà Nội",
  "Trường Cao đẳng Công nghệ và Quản trị Sonadezi",
  "Trường Cao đẳng Công nghiệp Cẩm Phả",
  "Trường Cao đẳng CĐ Hậu Giang",
  "Trường Cao đẳng Bình Thuận",
  "Trường Cao đẳng Hải Dương",
  "Trường Cao đẳng Công nghiệp thực phẩm (Phú Thọ)",
  "Trường Cao đẳng Kiên Giang",
  "Trường Cao đẳng Bình Định",
  "Trường Cao đẳng Kinh tế Công nghiệp Hà Nội",
  "Trường Cao đẳng Công nghiệp",
  "Trường Cao đẳng Điện lực TP. HCM",
  "Trường Cao đẳng Điện tử - Điện lạnh",
  "Trường Cao đẳng Công nghiệp Phúc Yên",
  "Trường Cao đẳng Giao thông vận tải II",
  "Trường Cao đẳng Kinh tế - Công nghệ TP. HCM",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Kiên Giang",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Quảng Nam",
  "Trường Cao đẳng Kinh tế - Kỹ thuật thương mại, Hà Nội",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Vinatex",
  "Trường Cao đẳng Kinh tế - Tài chính Thái Nguyên",
  "Trường Cao đẳng Kỹ thuật Cao Thắng",
  "Trường Cao đẳng Thương mại, Đà Nẵng",
  "Trường Cao đẳng Sư phạm Trung ương TP. HCM",
  "Trường Cao đẳng Công thương TP. HCM",
  "Trường Cao đẳng CN Việt – Hung",
  "Trường Cao đẳng Cộng đồng Đồng Tháp",
  "Trường Cao đẳng Y tế Bình Thuận",
  "Trường Cao đẳng Văn hoá nghệ thuật TP. HCM",
  "Trường Cao đẳng Cộng đồng Vĩnh Long",
  "Trường Cao đẳng Tài chính – Kế toán",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Lâm Đồng",
  "Trường Cao đẳng Kỹ thuật Lý Tự Trọng",
  "Trường Cao đẳng Y tế Hà Tĩnh",
  "Trường Cao đẳng Cơ điện – Nông nghiệp Nam Bộ",
  "Trường Cao đẳng Công nghệ (ĐH Đà Nẵng)",
  "Trường Cao đẳng Công nghiệp Huế",
  "Trường Cao đẳng Công nghiệp Nam Định",
  "Trường Cao đẳng Công nghiệp Tuy Hoà",
  "Trường Cao đẳng Công nghiệp Việt – Đức",
  "Trường Cao đẳng Giao thông vận tải III",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Cần Thơ",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Phú Lâm",
  "Trường Cao đẳng Kinh tế - Tài chính Vĩnh Long",
  "Trường Cao đẳng Kinh tế- Kế hoạch Đà Nẵng",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Nghệ An",
  "Trường Cao đẳng Tài chính – Hải quan",
  "Trường Cao đẳng Văn hóa nghệ thuật Nghệ An",
  "Trường Cao đẳng Công nghệ Thủ Đức",
  "Trường Cao đẳng Cộng đồng Hà Nội",
  "Trường Cao đẳng Công nghệ Bắc Hà",
  "Trường Cao đẳng Bách khoa Hưng Yên",
  "Trường Cao đẳng Nha khoa Hưng Yên",
  "Trường Cao đẳng Kinh tế - Kỹ thuật (ĐH Thái Nguyên)",
  "Trường Cao đẳng Cần Thơ",
  "Trường Cao đẳng Cộng đồng Bà Rịa – Vũng Tàu",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Thái Bình",
  "Trường Cao đẳng Văn hóa Nghệ thuật và Du lịch Sài Gòn",
  "Trường Cao đẳng Hàng hải 1",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Kon Tum",
  "Trường Cao đẳng Viễn Đông",
  "Trường Cao đẳng Bách Việt",
  "Trường Cao đẳng Kinh tế TP. HCM",
  "Trường Cao đẳng Cộng đồng Hà Tây",
  "Trường Cao đẳng Bến Tre",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Vĩnh Phúc",
  "Trường Cao đẳng Văn hóa Nghệ thuật Việt Bắc",
  "Trường Cao đẳng Du lịch Hà Nội",
  "Trường Cao đẳng Kỹ thuật Công nghiệp Quảng Ngãi",
  "Trường Cao đẳng CNTT Hữu nghị Việt – Hàn",
  "Trường Cao đẳng Cộng đồng Cà Mau",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Điện Biên",
  "Trường Cao đẳng Nông nghiệp Nam Bộ",
  "Trường Cao đẳng Công nghiệp Hưng Yên",
  "Trường Cao đẳng Giao thông vận tải TP. HCM",
  "Trường Cao đẳng Kinh tế đối ngoại",
  "Trường Cao đẳng Phương Đông (Đà Nẵng)",
  "Trường Cao đẳng Công Kỹ nghệ Đông Á",
  "Trường Cao đẳng Công nghiệp Thái Nguyên",
  "Trường Cao đẳng Nông Lâm Đông Bắc",
  "Trường Cao đẳng Tài nguyên và Môi trường miền Trung",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Phú Thọ",
  "Trường Cao đẳng Cộng đồng Sóc Trăng",
  "Trường Cao đẳng Xây dựng Nam Định",
  "Trường Cao đẳng Bán công Công nghệ và Quản trị doanh nghiệp",
  "Trường Cao đẳng Kỹ thuật Công nghiệp (Bắc Giang)",
  "Trường Cao đẳng Tư thục Đức Trí (Đà Nẵng)",
  "Trường Cao đẳng Bách Khoa Đà Nẵng",
  "Trường Cao đẳng Đại Việt",
  "Trường Cao đẳng Văn hóa Nghệ thuật và Du lịch Hạ Long",
  "Trường Cao đẳng Công nghệ và Thương mại Hà Nội",
  "Trường Cao đẳng Nghệ thuật Hà Nội",
  "Trường Cao đẳng Phương Đông, Quảng Nam",
  "Trường Cao đẳng Giao thông vận tải Miền trung",
  "Trường Cao đẳng Lạc Việt",
  "Trường Cao đẳng Công nghệ và Kinh tế Bảo Lộc",
  "Trường Cao đẳng Thương mại và Du lịch – Bộ Công thương",
  "Trường Cao đẳng Công nghệ và Kinh tế Hà Nội",
  "Trường Cao đẳng Du lịch và Thương mại – Bộ Công thương",
  "Trường Cao đẳng Thương mại và Du lịch Hà Nội",
  "Trường Cao đẳng Công nghệ Thông tin (ĐH Đà Nẵng)",
  "Trường Cao đẳng Công nghệ thông tin TP. HCM",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Hà Nội",
  "Trường Cao đẳng Điện lực Miền Trung",
  "Trường Cao đẳng Công nghiệp quốc phòng",
  "Trường Cao đẳng Công nghiệp hóa chất",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Trung ương",
  "Trường Cao đẳng Công nghiệp và Xây dựng – Bộ Công thương",
  "Trường Cao đẳng Kinh tế - Kỹ thuật Miền Nam",
  "Trường Cao đẳng Công nghệ và Kinh tế Công nghiệp",
  "Trường Cao đẳng Xây dựng công trình đô thị",
  "Trường Cao đẳng Đại Việt Sài Gòn",
  "Trường Cao đẳng Công nghệ và Kinh doanh Việt Tiến",
  "Trường Cao đẳng Kỹ thuật công nghệ Vạn Xuân",
  "Trường Cao đẳng Hoan Châu",
  "Trường Cao đẳng Công nghệ - Kinh tế và Thủy lợi Miền trung",
  "Trường Cao đẳng Kinh tế - Kỹ thuật TP. HCM",
  "Trường Cao đẳng ASEAN",
  "Trường Cao đẳng Cộng đồng Lào Cai",
  "Trường Cao đẳng Cộng đồng Bắc Kạn",
  "Trường Cao đẳng Phát thanh Truyền hình II",
  "Trường Cao đẳng Cộng đồng Lai Châu",
  "Trường Cao đẳng Ngô Gia Tự",
  "Trường Cao đẳng Văn hóa Nghệ thuật và Du lịch Yên Bái",
  "Trường Trung cấp Kỹ thuật Tin học Hà Nội ESTIH",
  "Trường Trung cấp Nông nghiệp Hà Nội",
  "Trường Trung cấp Kinh tế - Kỹ thuật Nông nghiệp Nam Định",
  "Trường Trung cấp Cơ điện Nam Định",
  "Trường Trung cấp Kinh tế - Kỹ thuật Hồng Lam",
  "Trường Trung cấp Tư thục Kinh tế - Kỹ thuật Đức Minh, Đà Nẵng",
  "Trường Trung cấp Kỹ thuật Nghiệp vụ Thăng Long, Đà Nẵng",
  "Trường Trung cấp Kinh tế - Kỹ thuật miền Trung, Đà Nẵng",
  "Trường Trung cấp Công nghệ và Kinh tế Hà Nội",
  "Trường Trung cấp Kinh tế - Kỹ thuật Lào Cai",
  "Trường Trung cấp Văn hóa Nghệ thuật Lạng Sơn",
  "Trường Trung cấp Kỹ thuật Nông nghiệp TP. HCM",
  "Trường Trung cấp Tư thục Tài chính tin học Ánh Sáng",
  "Trường Trung cấp Công nghiệp TP. HCM",
  "Trường Trung cấp Kinh tế - Kỹ thuật Bình Phước",
  "Trường Trung cấp Kinh tế - Kỹ thuật Long An",
  "Trường Trung cấp Kinh tế - Kỹ thuật Bạc Liêu",
  "Trường Trung cấp Kinh tế - Kỹ thuật Phương Đông",
  "Trường Trung cấp Bán công Bắc Thăng Long",
  "Trường Trung cấp Kỹ thuật và công nghệ (Nghệ An)",
  "Trường Trung cấp Thương mại Trung ương 5",
  "Trường Trung cấp Nông lâm (Thanh Hóa)",
  "Trường Trung cấp Tin học kinh tế Sài Gòn",
  "Trường Trung cấp Công nghệ Hải Phòng",
  "Trường Trung cấp Kinh tế - Kỹ thuật Bắc Giang",
  "Trường Trung cấp Kinh tế - Kỹ thuật Bình Định",
  "Trường Trung cấp Văn hóa nghệ thuật Bến Tre",
  "Trường Trung cấp Công nghệ Vĩnh Phúc",
  "Trường Trung cấp Kinh tế - Kỹ thuật Tây Ninh",
  "Trường Trung cấp Nghiệp vụ và công nghệ, Hải Phòng",
  "Trường Trung cấp Kỹ thuật xe – máy",
  "Trường Trung cấp Kinh tế Khánh Hòa",
  "Trường Trung cấp Phương Nam",
  "Trường Trung cấp Văn hóa – Nghệ thuật (Đà Nẵng)",
  "Trường Trung cấp Kỹ thuật và nghiệp vụ Nam Sài Gòn",
  "Trường Trung cấp Kinh tế, Kỹ thuật và Công nghệ Hải Phòng",
  "Trường Trung cấp Giao thông vận tải miền Bắc",
  "Trường Trung cấp Xây dựng miền Trung",
  "Trường Trung cấp Văn hóa nghệ thuật Bình Định",
  "Trường Trung cấp Cảnh sát nhân dân 1",
  "Trường Trung cấp Kinh tế - Kỹ thuật Tây Đô",
  "Trường Trung cấp Kinh tế - Kỹ thuật Hà Nội 1",
  "Trường Trung cấp Bưu chính viễn thông và CNTT 1",
  "Trường Trung cấp Mai Lĩnh Quảng Trị",
  "Trường Trung cấp Văn hóa nghệ thuật và du lịch Bình Dương",
  "Trường Trung cấp Kỹ thuật và công nghệ Cửu Long",
  "Trường Trung cấp Bưu chính viễn thông và CNTT miền núi",
  "Trường Trung cấp Nghiệp vụ quản lý lương thực thực phẩm",
  "Trường Trung cấp Kinh tế - Kỹ thuật Hòa Bình",
  "Trường Trung cấp Văn hóa – nghệ thuật Gia Lai",
  "Trường Trung cấp Quản lý và công nghệ",
  "Trường Trung cấp Thống kê 2",
  "Trường Trung cấp Kỹ thuật – nghiệp vụ Hải Phòng",
  "Trường Trung cấp Giao thông vận tải Huế",
  "Trường Trung cấp Nông nghiệp và PT nông thôn Hà Tĩnh",
  "Trường Trung cấp Văn hoá TT và DL Bắc Giang",
  "Trường Trung cấp Văn hoá nghệ thuật Nam Định",
  "Trường Trung cấp Nông lâm nghiệp Bình Dương",
  "Trường Trung cấp Kỹ thuật công nông nghiệp Quảng Bình",
  "Trường Trung cấp Kinh tế Quảng Bình",
  "Trường Trung cấp Kinh tế - Kỹ thuật Á Châu",
  "Trường Trung cấp Văn hóa nghệ thuật (Hà Tĩnh)",
  "Trường Trung cấp An ninh nhân dân 2",
  "Trường Trung cấp Tây Bắc (Bách Khoa Sài Gòn)",
  "Trường Trung cấp Xây dựng TP. HCM",
  "Trường Trung cấp Kinh tế CN Quảng Bình",
  "Trường Trung cấp Lâm nghiệp",
  "Trường Trung cấp Xây dựng Hà Nội",
  "Trường Trung cấp Kinh tế - Kỹ thuật Phương Nam",
  "Trường Trung cấp Kinh tế - Kỹ thuật Cà Mau",
  "Trường Trung cấp Kinh tế Đồng Nai",
  "Trường Trung cấp Đại Việt TP. HCM",
  "Trường Trung cấp Kinh tế - Kỹ thuật Tiền Giang",
  "Trường Trung cấp Công nghiệp Hà Nội",
  "Trường Trung cấp Việt – Nhật (Long An)",
  "Trường Trung cấp Kinh tế Du lịch – Duy Tân",
  "Trường Trung cấp Kinh tế Tài chính Hà Nội",
  "Trường Trung cấp Kinh tế - Kỹ thuật Sài Gòn",
  "Trường Trung cấp Hồng Hà",
  "Trường Trung cấp Kinh tế - Kỹ thuật Nguyễn Hữu Cảnh",
  "Trường Trung cấp Đông Dương",
  "Trường Trung cấp Đại Việt TP. Cần Thơ",
  "Trường Trung cấp Âu Việt",
  "Trường Trung cấp Đắk Lắk",
  "Trường Trung cấp Kỹ thuật – Nghiệp vụ Cái Bè",
  "Trường Trung cấp Âu Lạc – Huế",
  "Trường Trung cấp Kinh tế - Kỹ thuật Hà Giang",
  "Trường Trung cấp Kinh tế Bình Dương",
  "Trường Trung cấp Bách nghệ Cần Thơ",
  "Trường Trung cấp Bến Thành",
  "Trường Trung cấp Kinh tế - Công nghệ Cai Lậy (Tiền Giang)",
  "Trường Trung cấp Kinh tế - Kỹ thuật Đồng Nai",
  "Trường Trung cấp Kinh tế - Kỹ thuật Đắk Lắk",
  "Trường Trung cấp Phạm Ngọc Thạch (Cần Thơ)",
  "Trường Trung cấp Kỹ thuật Quân khí",
  "Trường Trung cấp Bách Khoa Gò Công",
  "Trường Trung cấp Kinh tế - Kỹ thuật Tây Nam Á",
  "Trường Trung cấp Văn hóa Nghệ thuật Thừa Thiên Huế",
  "Trường Trung cấp Tổng hợp TP. Hồ Chí Minh",
  "Trường Trung cấp Kinh tế - Kỹ thuật An Giang",
  "Trường Trung cấp Mỹ thuật – Văn hóa Bình Dương",
  "Trường Trung cấp Kỹ thuật Công binh",
  "Trường Trung cấp Kỹ thuật Thông tin",
  "Trường Trung học Văn hóa – Nghệ thuật Hải Phòng",
  "Trường Trung cấp Tân Bách Khoa",
  "Trường Trung cấp Tây Sài Gòn",
  "Trường Trung cấp Văn hóa Nghệ thuật Trà Vinh",
  "Trường Trung cấp Vạn Tường",
  "Trường Trung cấp Kinh tế - Kỹ thuật Hậu Giang",
];
